// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(WebAppMapsContext))]
    [Migration("20250606130803_Ajout_reunion_pause")]
    partial class Ajout_reunion_pause
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Etage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImgPlanEtagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Niveau")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Etages");
                });

            modelBuilder.Entity("Domain.Salle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("CoordX2BotRight")
                        .HasColumnType("float");

                    b.Property<double?>("CoordXTopLeft")
                        .HasColumnType("float");

                    b.Property<double?>("CoordY1TopLeft")
                        .HasColumnType("float");

                    b.Property<double?>("CoordY2BotRight")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("EtageId")
                        .HasColumnType("int");

                    b.Property<bool?>("Favori")
                        .HasColumnType("bit");

                    b.Property<string>("ImgSallePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("NbPlace")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EtageId");

                    b.ToTable("Salles");

                    b.HasDiscriminator().HasValue("Salle");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.SallePause", b =>
                {
                    b.HasBaseType("Domain.Salle");

                    b.Property<int>("Evier")
                        .HasColumnType("int");

                    b.Property<bool>("Frigo")
                        .HasColumnType("bit");

                    b.Property<int>("MicroOndes")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("SallePause");
                });

            modelBuilder.Entity("Domain.salleReunion", b =>
                {
                    b.HasBaseType("Domain.Salle");

                    b.Property<bool>("camera")
                        .HasColumnType("bit");

                    b.Property<bool>("ecran")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("salleReunion");
                });

            modelBuilder.Entity("Domain.Salle", b =>
                {
                    b.HasOne("Domain.Etage", "Etage")
                        .WithMany("Salles")
                        .HasForeignKey("EtageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etage");
                });

            modelBuilder.Entity("Domain.Etage", b =>
                {
                    b.Navigation("Salles");
                });
#pragma warning restore 612, 618
        }
    }
}
